config/routes.rb
Rails.application.routes.draw do
  root "visitors#index"

  devise_for :users, :controllers => { registrations: 'registrations' } do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  get "/app/builder/home" => "builder#index", :as => :builder
  get "/app/dashboard/home" => "dashboards#index", :as => :dashboard
  resources :users
  resources :projects
  get "select_project" => "projects#select_project", :as => :select_project
  get "/app/manage/devices" => "management#index", :as => :devices
  get "/app/manage/forms" => "management#index", :as => :forms
  get "/app/help" => "help#index", :as => :help

  scope "/api", :defaults => { :format => :json } do
    resources :choice_lists, except: [:edit, :new]
    # resources :clients, except: [:edit, :new]
    resources :connections, only: [:index, :show]
    resources :devices, only: [:index, :show]
    post "/connect/:pouch_code/device/:serial_number" => "devices#connect"
    resources :languages, except: [:edit, :new]
    resources :pouch_keys, except: [:edit, :new]
    resources :question_attributes, except: [:edit, :new]
    resources :question_categories, only: [:index, :show]
    resources :question_options, only: [:create, :index, :show]
    resources :question_types, except: [:edit, :new, :destroy]
    resources :questions, except: [:edit, :new]
    resources :schemas, except: [:edit, :new, :destroy]
    resources :sections, except: [:edit, :new]
    resources :survey_groups, except: [:edit, :new]
    resources :survey_families, except: [:edit, :new]
    put "/survey_families/:id/update_active" => "survey_families#update_active"
    post "/survey_families/:id/update_target" => "survey_families#update_target"
    resources :survey_family_joins, except: [:edit, :new]
    resources :survey_languages, except: [:edit, :new]
    resources :survey_targets, except: [:edit, :new]
    resources :surveys, except: [:edit, :new]
    post "/surveys/:id/publish_schema" => "surveys#publish_schema"
    post "/schemas/upload_schema" => "surveys#upload_schema"
    get "/surveys/:id/latest_schema" => "surveys#latest_schema"
    post "/surveys/:id/create_clone" => "surveys#create_clone"
    get "/surveys/:id/clones" => "surveys#clones"
    put "/surveys/:id/update_active" => "surveys#update_active"
    post "/surveys/:id/update_target" => "surveys#update_target"
    resources :translations, only: [:index, :show, :update]
    resources :users, only: [:index, :show]
    get "/current_user" => "users#current"
    get "/healthcheck" => "healthcheck#check_db"
  end

  get "*builder" => "builder#index"
  get "*dashboard" => "dashboards#index"
  get "*users" => "users#home"
  get "*help" => "help#index"

  

end

app/views/layouts/_footer.html.erb
<footer>
  Copyright MSI Inc. Client Innovations <%= Date.today.year %>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><a href="#">Hello, <%= current_user.name %>!</a></li>
  <li>
    <%= link_to edit_user_registration_path do %>
      <i class="fa fa-gear fa-fw"></i> Edit Account
    <% end %>
  </li>
  <li>
    <%= link_to destroy_user_session_path, :method=>'delete' do %>
      <i class="fa fa-sign-out fa-fw"></i> Logout
    <% end  %>
  </li>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

  <ul class="nav navbar-top-links navbar-left">
    <% if @ability.can? :see, :dashboards %>
    <li class="toggle-active <%= active_class('dashboards') %>">
      <%= link_to dashboard_path do %>
        <i class="fa fa-dashboard fa-fw"></i> Dashboards
      <% end %>
    </li>
    <% end %>
    <% if @ability.can? :see, :builder %>
    <li class="toggle-active <%= active_class('builder') %>">
      <%= link_to builder_path do %>
        <i class="fa fa-wrench fa-fw"></i> Form Builder
      <% end %>
    </li>
    <% end %>
    <% if @ability.can? :see, :all %>
    <li class="toggle-active <%= active_class('management') %>">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-cogs fa-fw"></i> System Management <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu">
        <li class="toggle-active">
          <%= link_to devices_path  do %>
            <i class="fa fa-tablet fa-fw"></i> Manage Devices
          <% end %>
        </li>
        <li class="toggle-active">
          <%= link_to forms_path  do %>
            <i class="fa fa-files-o fa-fw"></i> Manage Forms
          <% end %>
        </li>
        <li class="toggle-active">
          <%= link_to users_path  do %>
            <i class="fa fa-users fa-fw"></i> Manage Users
          <% end %>
        </li>
        <li class="toggle-active">
          <%= link_to projects_path  do %>
            <i class="fa fa-users fa-fw"></i> Manage Projects
          <% end %>
        </li>
      </ul>
    </li>
    <% end %>
  </ul>

  <ul class="nav navbar-top-links navbar-right">
    <li class="nav-item dropdown">
      <a class="dropdown-toggle" href="#" data-toggle="dropdown">Select Project <i class="fa fa-caret-down"></i></a> 
      <ul class="dropdown-menu">
        <% session[:project_list].each do |p| %>
          <li class="toggle-active">
            <%= link_to select_project_path+"?project_id="+p["id"].to_s do %>
              <%= p["name"] %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </li>
    
    <li class="toggle-active <%= active_class('help') %>">
      <%= link_to help_path do %>
        <i class="fa fa-life-ring fa-fw"></i> Help Docs
      <% end %>
    </li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </li>
  </ul>

  <% if @controller == "builder" || @controller == "dashboards" || @controller == "management" || @controller == "help" %>
  <div class="navbar-default sidebar fixed" role="navigation">
    <div class="cf">
      <a class="navbar-brand" href="/">
        <%= image_tag "logo/32x32.png", :class => "logo", :alt => "Myna Web" %> Myna - <%= @client.capitalize %>
      </a>
    </div>
    <div class="sidebar-nav navbar-collapse">
      <ui-view name="nav"></ui-view>
    </div>
  </div>
  <% else %>
  <div class="navbar-default sidebar static" role="navigation">
    <div class="cf">
      <a class="navbar-brand" href="/">
        <%= image_tag "logo/32x32.png", :class => "logo", :alt => "Myna Web" %> Myna - <%= @client.capitalize %>
      </a>
    </div>
    <div class="sidebar-nav navbar-collapse">
      <ui-view name="nav"></ui-view>
    </div>
  </div>
  <% end %>

</nav>


<script>
  (function(){
    var navs = document.querySelectorAll(".navbar-top-links .toggle-active");
    navs.forEach(function(nav){
      nav.addEventListener("click", function(e){
        navs.forEach(function(n){
          n.classList = "toggle-active";
        });
        nav.classList = "toggle-active active";
      });
    });
  }())
</script>

app/views/layouts/angular.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myna - <%= @client.capitalize %></title>
  <base href="/app/">
  <%= favicon_link_tag 'logo/16x16.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "app" %>
  <%= csrf_meta_tags %>
</head>
<body data-ng-app="formBuilder">
  <div id="wrapper">
    <% if user_signed_in? %>
      <%= render 'layouts/navigation' %>
      <div id="page-wrapper">
        <%= render 'layouts/messages' %>
        <flash-message class="flash">
          <div class="modal-overlay {{flash.config.class}}">
            <div role="alert" class="alert alert-{{flash.type}} {{flash.config.class}} alert-dismissible alertIn alertOut">
              <div type="button" class="close" ng-show="flash.showClose" close-flash="{{flash.id}}">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span>
              </div>
              <span dynamic="flash.text"></span>
            </div>
          </div>
        </flash-message>
        <%= yield %>
      </div>
    <% else %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    <% end %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myna - <%= @client.capitalize %></title>
  <%= favicon_link_tag 'logo/16x16.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <% if user_signed_in? %>
      <%= render 'layouts/navigation' %>
    <% end %>
    <div id="page-wrapper" class="no-margin">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>